# Generated by Django 3.0.7 on 2020-07-05 09:13
# python manage.py makemigrations 命令创建中间文件
# 通过python manage.py migrate 把表同步到数据库
# python manage.py migrate index 0001 回滚版本
# python manage.py inspectdb > 文件名.py 从数据库到处表类
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
        ),
    ]
