# Generated by Django 3.0.7 on 2020-07-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_author_isactive'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
