# Generated by Django 3.0.7 on 2020-07-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200712_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publicate_data',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, verbose_name='书籍名称'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='booK',
        ),
    ]
