# Generated by Django 3.0.5 on 2020-07-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200712_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publicate_data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
