# Generated by Django 3.0.7 on 2020-07-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20200714_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.author', verbose_name='相公')),
            ],
        ),
    ]
